### ISSUE TITLE
efficient token usage like taxyai is possible?

### ISSUE THREAD

**Issue by seshubonam** [BuilderIO/gpt-assistant#2]
https://github.com/TaxyAI/browser-extension 

Taxy runs a content script on the webpage to pull the entire DOM. It simplifies the html it receives to only include interactive or semantically important elements, like buttons or text. It assigns an id to each interactive element. 

can this work in gpt-assistant?

**Comment by steve8708** [comment]
this is the same way that gpt-assistant works as well - we send minimal HTML instead of the entire thing. have you found taxy's HTML to be more efficient than ours here? open to PRs with suggestions

**Comment by seshubonam** [comment]
great! will add pr for what we build too.

looking to build a mobile interface that automates browser actions and display a webview of the urls. wondering if devtools work with webview as well. 
would this implementation work with webview or does it specifically need a desktop browser access. 

(im non technical, asking for delegating the work)
